service: sample-app
provider:
    name: aws
    runtime: nodejs18.x
    stage: dev
    region: us-east-2
    memorySize: 128
functions:
    app:
        handler: server/index.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true
